In [1]:
import xarray as xr
import pandas as pd 
import numpy as np
import os
os.getcwd()

# data_path = '../../ktchris/Synthetic_Argo_Dataset/'
# synargo_4hourly = xr.open_dataset(data_path + 'Synthetic_Argo_Data_2014.nc')

'/global/cfs/cdirs/m4839/sangsong/crusoe_carbon_validation'

In [2]:

data_path = '../../ktchris/Synthetic_Argo_Dataset/'
synargo_4hourly = xr.open_dataset(data_path + 'Synthetic_Argo_Data_2014.nc')
synargo_4hourly

<xarray.Dataset> Size: 27GB
Dimensions:          (nVertLevels: 61, record: 2190, nParticles: 3544)
Coordinates:
  * nVertLevels      (nVertLevels) int64 488B 0 1 2 3 4 5 ... 55 56 57 58 59 60
  * record           (record) datetime64[ns] 18kB 2014-01-01 ... 2014-12-31T2...
Dimensions without coordinates: nParticles
Data variables: (12/19)
    lat              (record, nParticles) float64 62MB ...
    lon              (record, nParticles) float64 62MB ...
    ifrac            (record, nParticles) float64 62MB ...
    MLD              (record, nParticles) float64 62MB ...
    atmPressure      (record, nParticles) float64 62MB ...
    windStressMerid  (record, nParticles) float64 62MB ...
    ...               ...
    DIC              (nVertLevels, record, nParticles) float64 4GB ...
    ALK              (nVertLevels, record, nParticles) float64 4GB ...
    O2               (nVertLevels, record, nParticles) float64 4GB ...
    NO3              (nVertLevels, record, nParticles) float64 4GB ...
    fnum             (nParticles) float64 28kB ...
    Depth            (nVertLevels, record, nParticles) float64 4GB ...

In [14]:
combined = xr.open_dataset('./synArgo_10day_annual/synArgo_realworld_matches_10day_2014-2023.nc')

In [3]:
synargo_4hourly.pCO2surface

<xarray.DataArray 'pCO2surface' (record: 2190, nParticles: 3544)> Size: 62MB
[7761360 values with dtype=float64]
Coordinates:
  * record   (record) datetime64[ns] 18kB 2014-01-01 ... 2014-12-31T20:00:00
Dimensions without coordinates: nParticles
Attributes:
    units:         ppmv
    long_name:     sampled ocean pCO2 at the surface for particle
    cell_methods:  Time: mean

In [17]:
combined.sel({'fnum':5906030, 'nVertLevels':1}).to_dataframe().reset_index().dropna(subset=
                                                        ['lat'])

,profnum,lat,lon,ifrac,MLD,atmPressure,windStressMerid,windStressZonal,Salinity,Temperature,...,atmosphericCO2,DIC,ALK,O2,NO3,Depth,fnum,nVertLevels,nParticles_index,time
0,0,-49.483307,30.299854,0.0,96.010165,99156.644571,0.034485,0.549739,33.643772,6.105114,...,411.273678,2164.058594,2313.042725,306.956604,28.867435,-3.870059,5906030,1,2642,2019-05-01 08:00:00
1,1,-50.121695,30.636702,0.0,102.688235,100733.587506,0.204769,0.045094,33.637085,5.672830,...,411.356686,2165.831543,2312.624756,306.443024,29.248180,-4.022816,5906030,1,2642,2019-05-11 08:00:00
2,2,-50.252430,31.520966,0.0,98.521341,98676.122495,-0.081516,0.291595,33.634022,5.490104,...,411.439694,2165.958496,2312.116455,309.113586,29.393263,-3.878447,5906030,1,2642,2019-05-21 08:00:00
3,3,-49.972235,32.834420,0.0,105.642165,102024.395983,-0.017707,0.078636,33.631126,5.229555,...,411.522702,2167.341064,2311.650879,310.834686,29.707340,-4.127915,5906030,1,2642,2019-05-31 08:00:00
4,4,-49.664446,33.335577,0.0,108.547626,73430.837813,-0.065654,0.133502,33.634254,5.000121,...,411.605709,2168.762695,2311.073242,310.542969,30.065971,-3.824582,5906030,1,2642,2019-06-10 08:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,158,-51.863497,99.333946,0.0,134.724666,98910.866901,-0.235006,0.638555,33.762432,3.046870,...,421.080000,2201.148926,2326.527344,321.409180,33.110394,-3.858402,5906030,1,2642,2023-08-29 08:00:00
159,159,-51.572767,100.389447,0.0,125.836615,101412.338221,0.009906,0.010807,33.765850,3.025076,...,421.080000,2199.297119,2326.096436,324.114227,32.667908,-3.926557,5906030,1,2642,2023-09-08 08:00:00
160,160,-51.468200,101.056213,0.0,137.211419,99401.417444,0.231306,0.238591,33.775772,3.045743,...,421.080000,2198.011475,2325.711670,323.567719,32.169456,-3.921841,5906030,1,2642,2023-09-18 08:00:00
161,161,-51.689487,101.924867,0.0,116.457704,98386.145263,0.022560,0.136841,33.782959,2.843543,...,421.080000,2201.694580,2327.673340,325.320648,32.553619,-3.839250,5906030,1,2642,2023-09-28 08:00:00
162,162,-52.085619,103.096461,0.0,81.964519,100607.831133,-0.227949,-0.061201,33.788506,2.892721,...,421.080000,2203.563721,2328.577148,326.356354,32.752876,-3.878838,5906030,1,2642,2023-10-08 08:00:00

In [9]:
fdir = '/global/cfs/cdirs/m4839/ktchris/for_Song/'

# This file contains the date and time of all float profiles ever taken
# Downloaded from Coriolis
fname = 'ar_index_global_prof.txt'

# Put in the years that you are interested in
startyear = 2008
endyear = 2023

# Open the file as a Pandas dataset
# Create a datetime column rather individual than y, m, d columns
df = pd.read_csv(fdir+fname,sep=',',comment='#',header=0,usecols=[0,1,2,3])
df['datetime'] = pd.to_datetime(df.pop('date'),format='%Y%m%d%H%M%S')

# Create an index column that contains the float number
fnums = []
fnames = df.pop('file')
for filenum in range(len(fnames)):
    fnums.append(int(fnames.iloc[filenum].split('/')[1]))
df['fnum'] = fnums

df[df.fnum == 1900724]

       latitude  longitude            datetime     fnum
43261   -45.973   -161.966 2007-10-10 10:53:53  1900724
43262   -45.970   -161.999 2007-10-20 12:20:23  1900724
43263   -46.067   -162.067 2007-10-30 17:42:16  1900724
43264   -45.903   -161.967 2007-11-09 22:54:19  1900724
43265   -45.662   -161.750 2007-11-20 00:30:31  1900724
...         ...        ...                 ...      ...
43482   -51.961   -136.199 2013-12-04 06:23:35  1900724
43483   -51.954   -133.843 2013-12-14 10:18:45  1900724
43484   -52.756   -133.465 2013-12-24 14:28:25  1900724
43485   -53.679   -132.262 2014-01-03 15:42:43  1900724
43486   -54.242   -129.889 2014-01-13 19:45:50  1900724

[226 rows x 4 columns]

In [7]:
# foo.sel({'fnum':1900724, 'nVertLevels':1})
# foo
# foo = pd.read_csv('/global/cfs/cdirs/m4839/ktchris/for_Song/float_deployment_extended2008-2023_realworld.csv')
################# 
# foo = pd.read_parquet('./synArgo_59record_2000-2023deployments/float_deployment_realworld_annualrecords.parquet')
# foo = foo.reset_index()
foo[foo.fnum == 5904529]

,level_0,index,fnum,latitude,longitude,datetime,ptime,deplife,year,record_index,...,2014_records,2015_records,2016_records,2017_records,2018_records,2019_records,2020_records,2021_records,2022_records,2023_records
12729,12729,12729,5904529,-50.991,163.805,2013-12-09 12:22:22,2013-12-09 12:00:00,3084 days 12:00:00,2013,2055,...,"[42, 101, 160, 219, 278, 337, 396, 455, 514, 5...","[35, 94, 153, 212, 271, 330, 389, 448, 507, 56...","[28, 87, 146, 205, 264, 323, 382, 441, 500, 55...","[21, 80, 139, 198, 257, 316, 375, 434, 493, 55...","[14, 73, 132, 191, 250, 309, 368, 427, 486, 54...","[7, 66, 125, 184, 243, 302, 361, 420, 479, 538...","[0, 59, 118, 177, 236, 295, 354, 413, 472, 531...","[52, 111, 170, 229, 288, 347, 406, 465, 524, 5...","[45, 104, 163, 222, 281, 340, 399, 458, 517, 5...",None

In [13]:
foo.sel({'fnum':1900951, 'nVertLevels':1}).to_dataframe().reset_index().dropna(subset=
                                                        ['lat'])

# single.year.sel({'fnum':1900951, 'nVertLevels':1}).to_dataframe().reset_index().dropna(subset=
#                                                         ['lat'])

,profnum,fnum,nParticles_index,time,lat,lon,ifrac,MLD,atmPressure,windStressMerid,...,Temperature,CO2_gas_flux,pCO2surface,dpCO2,atmosphericCO2,DIC,ALK,O2,NO3,Depth
0,0,1900951,2788,2015-01-05,31.788844,27.956127,0.0,100.035184,101595.809813,0.146292,...,19.578228,8.755405e-05,375.529251,-24.310486,398.773940,2231.128662,2569.585449,225.230850,0.030900,-4.036014
1,1,1900951,2788,2015-01-15,31.795451,27.998911,0.0,132.658405,101827.198274,-0.065855,...,18.366413,4.869350e-05,361.399637,-39.416878,398.839741,2230.656494,2564.384521,230.343506,0.074921,-4.080438
2,2,1900951,2788,2015-01-25,31.793200,28.010764,0.0,97.838523,101469.241237,0.053745,...,18.115631,3.736323e-05,359.503154,-39.970250,398.905542,2230.593506,2562.266846,231.953247,0.077143,-3.974383
3,3,1900951,2788,2015-02-04,31.795286,28.021419,0.0,169.833383,101984.691506,-0.001926,...,17.743034,1.941903e-05,356.827273,-44.741633,398.971343,2230.339844,2559.358154,232.580017,0.178375,-3.954469
4,4,1900951,2788,2015-02-14,31.798007,28.039244,0.0,170.290578,101740.202611,-0.020382,...,17.268394,3.624039e-05,353.402041,-47.270250,399.037144,2229.584473,2555.161865,233.693344,0.284846,-4.016321
5,5,1900951,2788,2015-02-24,31.794125,28.038982,0.0,157.091928,101114.333958,0.049313,...,17.004599,4.113768e-05,350.957453,-47.315712,399.102945,2229.453369,2553.674561,235.521713,0.293665,-4.043248
6,6,1900951,2788,2015-03-06,31.794985,28.042507,0.0,41.288216,102058.257851,0.010643,...,17.158028,3.326525e-05,350.778674,-51.278733,399.168746,2229.126221,2555.300293,239.125443,0.034106,-4.132078
7,7,1900951,2788,2015-03-16,31.794198,28.051539,0.0,57.290405,102367.881381,-0.072739,...,17.159338,6.260370e-05,352.366051,-50.977593,399.234547,2230.216553,2555.344238,239.183685,0.033616,-4.126623
8,8,1900951,2788,2015-03-26,31.787123,28.042405,0.0,37.846380,101553.713720,0.039087,...,17.253998,1.014585e-04,354.431446,-45.770214,399.300347,2231.951660,2556.975586,239.192490,0.040560,-4.085235
9,9,1900951,2788,2015-04-05,31.788135,28.040911,0.0,14.201650,101525.714570,0.001525,...,17.579788,4.623098e-06,359.864739,-40.292514,399.366148,2230.708252,2554.911377,238.865158,0.027142,-4.082847
10,10,1900951,2788,2015-04-15,31.790484,28.063030,0.0,14.509204,101773.496070,-0.011123,...,17.331390,6.348363e-06,357.832720,-43.367240,399.431949,2231.372559,2554.343994,239.451462,0.025487,-4.155842
11,11,1900951,2788,2015-04-25,31.788787,28.058369,0.0,23.038130,102247.695594,0.002000,...,17.774481,8.110568e-06,366.308545,-36.827150,399.497750,2233.134277,2555.275879,238.911621,0.006553,-4.177227
12,12,1900951,2788,2015-05-05,31.785764,28.059061,0.0,6.565918,101394.653218,-0.011370,...,18.682478,2.785584e-06,381.845596,-17.992625,399.563551,2235.062744,2556.796143,236.435654,0.002997,-4.046920
13,13,1900951,2788,2015-05-15,31.784547,28.059582,0.0,13.279780,101846.174249,-0.018049,...,19.953440,-8.675844e-07,402.921331,1.236450,399.629352,2235.493408,2557.375977,232.858200,0.001893,-4.105200
14,14,1900951,2788,2015-05-25,31.783726,28.058739,0.0,5.732116,101314.117160,-0.034490,...,21.244644,-1.689270e-05,424.818937,25.166713,399.695153,2236.534668,2559.194580,228.998657,0.001606,-4.001242
15,15,1900951,2788,2015-06-04,31.784371,28.062080,0.0,14.881060,101591.163086,-0.026216,...,21.643053,-2.767685e-05,430.834206,30.023150,399.760954,2235.746338,2559.092285,225.087997,0.001417,-4.029104
16,16,1900951,2788,2015-06-14,31.781624,28.056403,0.0,11.328300,101422.188163,-0.021639,...,22.929741,-2.601978e-05,453.157724,52.947466,399.826755,2235.687012,2560.141602,221.011627,0.001446,-4.027199
17,17,1900951,2788,2015-06-24,31.780623,28.053460,0.0,14.885666,101332.444152,-0.029406,...,23.897295,-4.469127e-05,469.571033,69.649098,399.892556,2234.682861,2560.507080,216.646439,0.001354,-3.959981
18,18,1900951,2788,2015-07-04,31.779810,28.055497,0.0,22.912096,101333.738649,-0.045660,...,24.429865,-7.512716e-05,477.692442,77.696470,399.961478,2233.718750,2560.994873,213.834045,0.001368,-3.945674
19,19,1900951,2788,2015-07-14,31.779871,28.056480,0.0,23.406544,100922.909676,-0.043658,...,25.181761,-8.651099e-05,489.869071,91.408311,400.048281,2232.756592,2561.918213,210.115784,0.001441,-3.912732
20,20,1900951,2788,2015-07-24,31.779106,28.057558,0.0,11.842066,100815.339777,-0.020137,...,25.945404,-3.559660e-05,504.783429,106.661007,400.135083,2233.217285,2563.331055,208.707184,0.001609,-3.864656
21,21,1900951,2788,2015-08-03,31.780552,28.064660,0.0,8.357847,101051.021616,-0.023417,...,27.038857,-5.248795e-05,526.267312,127.127608,400.221886,2233.197998,2564.737549,206.142609,0.001724,-3.874931
22,22,1900951,2788,2015-08-13,31.778742,28.064719,0.0,14.556192,101140.539547,-0.012499,...,27.813728,-3.547912e-05,541.955719,142.375785,400.308689,2233.403320,2566.154785,204.344971,0.001674,-3.852986
23,23,1900951,2788,2015-08-23,31.777862,28.063314,0.0,24.035771,100921.974750,-0.040316,...,28.100384,-1.210494e-04,544.937787,146.134888,400.395492,2232.566406,2567.144775,201.940170,0.001473,-3.863951
24,24,1900951,2788,2015-09-02,31.773882,28.053678,0.0,24.691414,101300.687432,-0.009393,...,27.839914,-2.333842e-05,534.857092,134.470891,400.482295,2232.511230,2569.818604,199.971313,0.001649,-3.906248
25,25,1900951,2788,2015-09-12,31.773247,28.048284,0.0,25.497792,101425.544510,-0.041935,...,27.895630,-9.776090e-05,533.593033,132.626452,400.569098,2232.511475,2571.380615,199.691925,0.001709,-3.864584
26,26,1900951,2788,2015-09-22,31.770888,28.041819,0.0,33.072480,100755.878013,0.048131,...,27.743063,-1.333078e-04,530.619129,132.213631,400.655901,2232.734131,2571.355957,201.458267,0.001710,-3.820049
27,27,1900951,2788,2015-10-02,31.771724,28.040149,0.0,34.098005,101756.757847,-0.026072,...,27.532698,-5.353876e-05,524.333971,121.883656,400.742704,2232.844971,2572.556641,201.444641,0.001939,-3.892687
28,28,1900951,2788,2015-10-12,31.770505,28.037576,0.0,34.664369,101382.669233,0.020809,...,26.900143,-4.020545e-05,509.620493,108.562855,400.829506,2233.253418,2573.973633,202.235016,0.002132,-3.814710
29,29,1900951,2788,2015-10-22,31.768275,28.030221,0.0,38.087201,101162.783515,0.040449,...,26.435219,-7.160303e-05,500.260198,99.985737,400.916309,2234.160156,2574.970947,203.695160,0.002661,-3.806776
30,30,1900951,2788,2015-11-01,31.769023,28.028393,0.0,44.196893,102073.836250,-0.024309,...,25.393219,-5.129392e-05,478.618450,74.651749,401.003112,2233.268799,2573.929932,205.739594,0.003878,-3.897332
31,31,1900951,2788,2015-11-11,31.767010,28.020620,0.0,48.623858,101770.034347,-0.064922,...,24.079771,-5.818777e-05,452.916146,50.064585,401.089915,2232.998779,2573.482666,209.519241,0.005874,-3.975977
32,32,1900951,2788,2015-11-21,31.766270,28.017288,0.0,50.016005,101806.324559,0.000566,...,23.298552,-1.949203e-06,439.244150,36.161721,401.176718,2233.368408,2573.158936,212.145020,0.007191,-3.980640
33,33,1900951,2788,2015-12-01,31.767238,28.013393,0.0,61.040775,102076.142151,-0.128430,...,22.423117,-4.325784e-05,424.663354,20.425188,401.263521,2234.051025,2572.926025,215.218384,0.010707,-3.878658
34,34,1900951,2788,2015-12-11,31.764677,28.007431,0.0,71.041924,102257.041521,-0.043895,...,21.286165,-1.314140e-06,406.539308,1.497150,401.350324,2235.200928,2572.824219,219.624390,0.018662,-4.038256
35,35,1900951,2788,2015-12-21,31.764512,28.012996,0.0,68.473938,102680.814946,-0.026640,...,20.337269,7.277670e-06,391.424006,-15.384692,401.437126,2233.802979,2569.926025,222.700760,0.030554,-4.013267
36,36,1900951,2788,2015-12-31,31.766161,28.024285,0.0,83.482862,101755.505922,-0.099148,...,19.791718,3.252564e-05,383.672763,-19.557146,401.523929,2234.516357,2569.658203,225.371399,0.034894,-4.012857

In [4]:
deployINDEX = pd.read_csv('/global/cfs/cdirs/m4839/sangsong/crusoe_carbon_validation/float_deployment_realworld_annualrecords.csv', index_col=0)
deployINDEX = deployINDEX.dropna(subset = ['nParticles_index'])

In [11]:
# deployINDEX = deployINDEX.dropna(subset = ['nParticles_index'])
    # [deployINDEX.nParticles_index.isna()]

In [ ]:
# data_path = '../../ktchris/Synthetic_Argo_Dataset/'
# ds_4hourly = xr.open_dataset(data_path + 'Synthetic_Argo_Data_2014.nc')

In [12]:
import ast
yr = 2014
yrcol = f'{yr}_records'
# data_path = '../../ktchris/Synthetic_Argo_Dataset/'
# synargo_4hourly = xr.open_dataset(data_path + 'Synthetic_Argo_Data_'+ str(yr) + '.nc')

print('Retrieving float data for year ' + str(yr) + ': ', datetime.now().strftime('%Y%m%d %H:%M'))

# Retrieve floats that have data for this given year
yearINDEX = deployINDEX[~deployINDEX[yrcol].isna()]
print('Processing ' + str(len(yearINDEX)) + ' valid floats...')

# Iterate over each float using that years 
fnumDatasets = []
for fnum in yearINDEX.index:
    record_list_4hourly = ast.literal_eval(yearINDEX.loc[fnum][yrcol])
    record_list = record_list_4hourly[::int(10*24/4)]

    nParticles_index = int(yearINDEX.loc[fnum]['nParticles_index'])
    floatDS = synargo_4hourly.isel(record=record_list, nParticles = nParticles_index)
    
    fnum_val = int(floatDS['fnum'].values.tolist())
    fnumDatasets.append(floatDS.assign_coords(fnum=fnum_val))

annualDS = xr.concat(fnumDatasets, dim='fnum')
annualDS.to_netcdf('./synArgo_10day_annual/synArgo_realworld_matches_10day_yr' + str(yr) + '.nc')
print('Finished retrieving year ' + str(yr) + ': ', datetime.now().strftime('%Y%m%d %H:%M'))

Retrieving float data for year 2014:  20261002 12:41
Processing 1018 valid floats...

KeyboardInterrupt:

In [9]:
yearINDEX.loc[fnum]

latitude                                                       12.521
longitude                                                     152.942
datetime                                          2014-12-31 22:41:05
ptime                                             2015-01-01 00:00:00
deplife                                            1000 days 00:00:00
year                                                             2014
record_index                                                        0
nParticles_index                                                  NaN
2014_records        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
2015_records        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
2016_records        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
2017_records                                                      NaN
2018_records                                                      NaN
2019_records                                                      NaN
2020_records                                                      NaN
2021_records                                                      NaN
2022_records                                                      NaN
2023_records                                                      NaN
Name: 5904910, dtype: object

In [48]:
# newlist = []
# for i, ds in enumerate(annualDS):
#     fnum_val = int(ds['fnum'].values.tolist())
#     newlist.append(ds.assign_coords(fnum=fnum_val))

# combined = xr.concat(newlist, dim='fnum')

In [4]:
data_path = '../../ktchris/Synthetic_Argo_Dataset/floats'
list = os.listdir(data_path)
list[-5:]

['Synth3902403_201912021200.nc',
 'Synth5902222_201002040400.nc',
 'Synth5900560_200408020000.nc',
 'Synth5903486_201010280800.nc',
 'Synth3900264_200503261200.nc']

In [3]:
foo = xr.open_dataset('../../ktchris/Synthetic_Argo_Dataset/floats/' + 'Synth3902403_201912021200.nc')
foo

<xarray.Dataset> Size: 349kB
Dimensions:          (nVertLevels: 61, record: 99, nParticles: 1)
Coordinates:
  * nVertLevels      (nVertLevels) int64 488B 0 1 2 3 4 5 ... 55 56 57 58 59 60
  * record           (record) datetime64[ns] 792B 2019-12-02T12:00:00 ... 202...
Dimensions without coordinates: nParticles
Data variables: (12/19)
    lat              (record, nParticles) float64 792B ...
    lon              (record, nParticles) float64 792B ...
    ifrac            (record, nParticles) float64 792B ...
    MLD              (record, nParticles) float64 792B ...
    atmPressure      (record, nParticles) float64 792B ...
    windStressMerid  (record, nParticles) float64 792B ...
    ...               ...
    DIC              (nVertLevels, record, nParticles) float64 48kB ...
    ALK              (nVertLevels, record, nParticles) float64 48kB ...
    O2               (nVertLevels, record, nParticles) float64 48kB ...
    NO3              (nVertLevels, record, nParticles) float64 48kB ...
    fnum             (record, nParticles) float64 792B ...
    Depth            (nVertLevels, record, nParticles) float64 48kB ...